### ISSUE TITLE
Crate cannot be compiled on MacOS

### ISSUE THREAD

**Issue by dfioravanti** [console-rs/console#170]
Hey everyone, first at all thanks for this great library. It looks really cool. I was playing around with `indicatif` and the compilation crashed with the following error

```
error[E0308]: mismatched types
   --> <path_to_cargo>/registry/src/github.com-1ecc6299db9ec823/console-0.15.6/src/unix_term.rs:149:35
    |
149 |             Ok(libc::FD_ISSET(fd, &read_fd_set))
    |                --------------     ^^^^^^^^^^^^ types differ in mutability
    |                |
    |                arguments to this function are incorrect
    |
    = note: expected raw pointer `*mut fd_set`
                 found reference `&fd_set`
note: function defined here
   --> <path_to_cargo>/registry/src/github.com-1ecc6299db9ec823/libc-0.2.86/src/unix/bsd/mod.rs:536:12
    |
536 |     pub fn FD_ISSET(fd: ::c_int, set: *mut fd_set) -> bool {
    |            ^^^^^^^^
```

I tried downgrading `libc` to `0.2.30` but that does not solve the problem. One can see [here](https://github.com/rust-lang/libc/blob/0.2.30/src/unix/bsd/mod.rs) that the signature for the function is identical.

**Comment by mitsuhiko** [comment]
Turns out the lower bound of 0.2.30 is broken. It needs at least 0.2.99. I will fix this.

**Comment by dfioravanti** [comment]
With that bounds it builds, thanks a lot
