### ISSUE TITLE
Release a new version to get rid of windows-sys 0.45?

### ISSUE THREAD

**Issue by zh-jq-b** [console-rs/console#175]
This is the last crate that depends on windows-sys 0.45 / windows-targets 0.42 in our project. Is it possible to just release a new version?

**Comment by Yatekii** [comment]
This would be most welcome 🙏

**Comment by mitsuhiko** [comment]
I will have a look if I can do that. For whatever reason last time I tried to bump it, i ran into some issues.

**Comment by Yatekii** [comment]
Thanks! I can PR it if it helps :) I am not sure if you have some specific procedure to make releases tho :)

**Comment by zh-jq-b** [comment]
@mitsuhiko are you still looking at this? It seems there are also some bug fixing pull requests waiting for a review.

**Comment by barrbrain** [comment]
Due to the `windows-sys` migration to Rust 2021 Addition, MSRV will also need to bump to 1.56.

**Comment by zh-jq-b** [comment]
close as the new version is available
